# SQL Interview Questions  - Quiz


## Introduction

This quiz contains questions on topics you can expect to see in an interview pertaining to SQL and Relational Databases. Some of them are multiple choice, while some are short answer. For these short answer questions, double click on the Jupyter Notebook and type your answer below the line. 

## Question 1

What are the 4 main datatypes in SQLite3? Can we use other common types from other kinds of SQL?

Type your answer below this line:
_______________________________________________________________________________________________________________________________

1. TEXT
2. INTEGER
3. BLOB
4. REAL
Generally, yes we can use data types from other types of SQL, as long as they can explicitly convert into one of the 4 listed above. For example another version may have "INT" for Integers whereas SQLite3 uses INTEGER.



## Question 2

Explain the relationship between **Primary Keys** and **Foreign Keys**.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Primary Keys are unique values within a table used as identifiers, a foreign key is a column that acts as the Primary key for another table. This allows for alot of relational DB stuff to occur, such as simple joins.




## Question 3

Explain the different types of relationships entities can have in a SQL database. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
One-to-One: These are when one item in a table directly ties to one other item in another table.
One-to-Many: These are when one item can tie to multiple different items, for example in the Data.sqlite example we had 1 product, however this can tie to many different order details, but each order detail ties back to a product.
Many-to-Many: These are when a table has multiple values which can be tied to multiple values on another table, such as if we had an employee who works from 3 different offices, tying their employee row to the offices table we will retreive 3 copies of the row with different offices if queried.



## Question 4

Explain the various types of JOINs possible with SQL. 

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Left: This is where it keeps all values on the left column and only brings the values that match from the right
Right: This is the opposite of the left join, it returns all values that match directly to the table on the right, does not return values that do not match.
Inner: Drops all values that do not match, i.e. if there are not direct relationships between rows it does not display them
Outer: This just puts both tables together regardless of matches with keys, it ties together values that do match, but also inserts rows that may be missing data if there are no matches.


## Question 5

Explain the relationship between Aggregate functions and GROUP BY statements.

Type your answer below this line:
_______________________________________________________________________________________________________________________________
Aggregate functions allow the GROUP BY statements to have context, for example if we are GROUP BY AVG(AVG) this will make sure all of the values are grouped together so we do not have multiple rows with averages.


## Question 6

What role do Associative Entities play (JOIN Tables) in many-to-many JOINs?


Type your answer below this line:
_______________________________________________________________________________________________________________________________
These act as an itermediary table which holds both tables' primary keys for reference, kind of 'ties' them together using a table. For example if we look at our student DB, we may have an associative entity that has the StudentID, CourseID, and Grades which would specify which course each student was in with the corresponding grade since we may have multiple students who are taking the same course or students taking multiple courses.


## Summary

In this lesson, we practiced answering open-ended interview questions for SQL and Relational Databases.